- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required
  ignore_errors: true
  tags:
    - checks
    - reboot_required

- name: Gather packages requiring reboot
  shell: cat /var/run/reboot-required.pkgs
  register: reboot_packages
  ignore_errors: true
  changed_when: false
  when: reboot_required.stat.exists
  tags: 
    - checks
    - reboot_packages

- name: Display packages requiring reboot
  debug:
    msg: "Packages requiring reboot: {{ reboot_packages.stdout | default('') }}"
  when: reboot_packages.stdout is defined and reboot_packages.stdout | default('') != ''
  ignore_errors: true
  tags:
    - checks
    - reboot_packages

- name: Schedule and warn users about impending reboot
  command: shutdown -r {{ reboot_schedule_time }} "System will be rebooted at {{ reboot_schedule_time }}. Please save your work and log out."
  async: 0
  poll: 0
  become: true
  when: reboot_required.stat.exists
  tags:
    - schedule